POST http://localhost:3002/user/login
Content-Type: application/json

{
    "username" : "tai",
    "password" : "123"
}

###
GET http://localhost:3002/user/getall
Content-Type: application/json
X-Token : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhaSIsImlkIjo2LCJobyI6InRydW9uZyIsInRlbiI6InRhaSIsImlzbG9ja2VkIjpmYWxzZSwibG9haXVzZXJpZCI6MSwidXNlcl9yb2xlcyI6W3sicm9sZWlkIjoxLCJ1c2VyaWQiOjYsInJvbGVzIjp7Im5hbWUiOiJBRE1JTiJ9fV0sImlhdCI6MTY3MTUyNTA3MiwiZXhwIjoxNjcxNTI1MDgyfQ.ojyWQc4CWrJTZHcFqvixVWd_MVRzLsVzVXrFPWjQWYY"



###

# GET http://localhost:3001/product/getProduct
# Content-Type: application/json

# {
#     "page" : 1,
#     "elementOfPage":2,
#     "options" : {
#         "loaisanphamid" : 2,
#         "book" : {
#             "ngonngu" : 1,
#             "tacgia" : 1,
#             "theloai" : 1,
#             "nhaphathanh" : 1,
#             "namxuatban" : 2010
#         },
#         "stationery" : {
#             "thuonghieu" : "a",
#             "xuatxu" : "a",
#             "kieudang" : "a",
#             "loaivpp" : 1
#         }
        
#     }
    
#     //"token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiYWRtaW4iLCJpYXQiOjE2Njk5MDM1NDgsImV4cCI6MTY2OTkwMzU1OH0.BoMdEWv0hFudqWOxlMzRtpVWAHUeUMUgYDE1mrdGE6A"
# }


###

GET http://localhost:3001/product/getProduct
Content-Type: application/json

{
    "page" : 1,
    "elementOfPage":10,
    "ten":"thân con"
    //"token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiYWRtaW4iLCJpYXQiOjE2Njk5MDM1NDgsImV4cCI6MTY2OTkwMzU1OH0.BoMdEWv0hFudqWOxlMzRtpVWAHUeUMUgYDE1mrdGE6A"
}


###
POST http://localhost:3002/user/newUser
Content-Type: application/json

{
    "username" : "tien123",
    "email":"abcc",
    "password" : "123"
}

###
POST http://localhost:3001/user/refreshToken
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjY5OTA0MDA5LCJleHAiOjE2NzA3NjgwMDl9.PSNY80c0OFwoSaKkfyZ9Op0eOObYoATkAX_vlABjN0o"
}






###

POST http://localhost:3001/cart/setCart
Content-Type: application/json

{
    "username" : "admin",
    "item" : "pencil",
    "count" : "10"
}


###


###

POST http://localhost:3002/user/verifyotpfogotpass
Content-Type: application/json

{
   
        "email" : "ntbang0901@gmail.com",
        "otp":384636
        
    
}

###

POST http://localhost:3002/user/updatepasss
Content-Type: application/json

{
   
        "data":{
            "email" : "ntbang0901@gmail.com",
            "password":"123"
        }
        
    
}



###
GET http://localhost:3001/cart/getCart
Content-Type: application/json

{
    "username" : "bang"
}

###
GET http://localhost:3002/cart/gettotalcart
Content-Type: application/json

{
    "username" : "bang"
}





###
POST http://localhost:3002/user/newuser
Content-Type: application/json

{
    "user":{
    "ho" : "ta",
    "ten" : "tien",
    "ngaysinh" : "09/12/2001",
    "gioitinh" : true,
    "diachi" : "XL",
    "sdt" : "0982345444",
    "email" : "ntbang0901@gmail.com",
    "username" : "nguyenthanhbang",
    "password" : "nguyenthanhbang",
    "isactived" :true
    }
}


###

POST http://localhost:3001/user/verifyOTP
Content-Type: application/json

{
    "email" : "tien101100",
    "otp" : "168632"
}